name: Förbättringar/Fel
description: Färbättringar/Fel
title: "[Tip]: I want "
labels: [Tip, enhancement]
assignees:
  - Xebilon
body:
  - type: markdown
    attributes:
      value: |
        Finns de något som är fel, eller vill du ändra något?
  - type: input
    id: Name
    attributes:
      label: Förbättring
      description: Vad behöver fixas?
      placeholder: Issue Form
    validations:
      required: true

  - type: textarea
    id: info
    attributes:
      label: Mer info
      description: Beskriv vad du önskar
      render: shell
    validations:
      required: true

  - type: dropdown
    id: Level
    attributes:
      label: Vad är det för typ av ärende?
      description: 
      options:
        - Förbättring
        - Felanmälan
        - Övrigt
    validations:
      required: true
